export const SCREENS = {
  GET_STARTED_SCREEN: 'IntroScreen',
  ON_BOARDING_SCREEN: 'OnBoarding',
  LOGIN_SCREEN: 'Login',
  REGISTER_SCREEN: 'Register',
  OTP_SCREEN: 'OtpScreen',
  MAIN_SCREEN: 'Main',
  REDIRECT: 'ReDirect',
  ViewDetails_Screen: 'ViewDetails',
  AddNewGoal_Screen: 'AddNewGoal',
  BookClasses_Screen: 'BookClasses',
  ENROLL_SCREEN: 'EnrollScreen',
  SCHOOL_SCREEN: 'School',
  SELECT_SCHOOL: 'SelectSchool',
  NOTIFICATION_SCREEN: 'Notification',
  UPCOMING_EVENTS_SCREEN: 'UpcomingEvents',
  LIFE_SKILL_HACKS: 'LifeSkillHacks',
  FEATURED_SERVICES: 'FeaturedServices',
};
